-- Aliyun 初始化脚本
-- 该脚本用于在 Docker Compose 的 MySQL 容器中初始化数据库和建表

SET NAMES utf8mb4;
SET CHARACTER SET utf8mb4;
SET collation_connection = utf8mb4_unicode_ci;

CREATE DATABASE IF NOT EXISTS amazingdata_etf
  DEFAULT CHARACTER SET utf8mb4
  DEFAULT COLLATE utf8mb4_unicode_ci;

USE amazingdata_etf;

CREATE TABLE IF NOT EXISTS etf_security_master (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    etf_code VARCHAR(16) NOT NULL COMMENT 'ETF代码，格式如510300.SH/159919.SZ',
    market VARCHAR(8) NOT NULL COMMENT '市场，SH/SZ',
    symbol VARCHAR(64) NULL COMMENT 'ETF简称',
    security_status VARCHAR(64) NULL COMMENT '产品状态标志，原始值可多值拼接',
    pre_close DECIMAL(24,6) NULL COMMENT '昨收价',
    high_limited DECIMAL(24,6) NULL COMMENT '涨停价',
    low_limited DECIMAL(24,6) NULL COMMENT '跌停价',
    price_tick DECIMAL(24,6) NULL COMMENT '最小价格变动单位',
    is_active TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否有效，1有效 0无效',
    list_date DATE NULL COMMENT '上市日期，如后续可补充',
    delist_date DATE NULL COMMENT '退市日期，如后续可补充',
    source VARCHAR(64) NOT NULL DEFAULT 'AmazingData' COMMENT '数据来源',
    etl_batch_no VARCHAR(64) NULL COMMENT 'ETL批次号',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (id),
    UNIQUE KEY uk_etf_code (etf_code),
    KEY idx_market (market),
    KEY idx_symbol (symbol),
    KEY idx_is_active (is_active)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='ETF基础信息主表';

CREATE TABLE IF NOT EXISTS trade_calendar (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    market VARCHAR(8) NOT NULL COMMENT '市场，SH/SZ/BJ等',
    trade_date DATE NOT NULL COMMENT '交易日',
    is_open TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否开市，1开市 0休市',
    source VARCHAR(64) NOT NULL DEFAULT 'AmazingData' COMMENT '数据来源',
    etl_batch_no VARCHAR(64) NULL COMMENT 'ETL批次号',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (id),
    UNIQUE KEY uk_market_trade_date (market, trade_date),
    KEY idx_trade_date (trade_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='交易日历表';

CREATE TABLE IF NOT EXISTS etf_market_snapshot (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    etf_code VARCHAR(16) NOT NULL COMMENT 'ETF代码',
    trade_time DATETIME(3) NOT NULL COMMENT '交易所行情时间，精确到毫秒',
    pre_close DECIMAL(24,6) NULL COMMENT '昨收价',
    last_price DECIMAL(24,6) NULL COMMENT '最新价',
    open_price DECIMAL(24,6) NULL COMMENT '开盘价',
    high_price DECIMAL(24,6) NULL COMMENT '最高价',
    low_price DECIMAL(24,6) NULL COMMENT '最低价',
    close_price DECIMAL(24,6) NULL COMMENT '收盘价',
    volume BIGINT NULL COMMENT '成交总量',
    amount DECIMAL(24,4) NULL COMMENT '成交总金额',
    num_trades BIGINT NULL COMMENT '成交笔数',
    high_limited DECIMAL(24,6) NULL COMMENT '涨停价',
    low_limited DECIMAL(24,6) NULL COMMENT '跌停价',
    ask_price1 DECIMAL(24,6) NULL COMMENT '卖1价',
    ask_price2 DECIMAL(24,6) NULL COMMENT '卖2价',
    ask_price3 DECIMAL(24,6) NULL COMMENT '卖3价',
    ask_price4 DECIMAL(24,6) NULL COMMENT '卖4价',
    ask_price5 DECIMAL(24,6) NULL COMMENT '卖5价',
    ask_volume1 BIGINT NULL COMMENT '卖1量',
    ask_volume2 BIGINT NULL COMMENT '卖2量',
    ask_volume3 BIGINT NULL COMMENT '卖3量',
    ask_volume4 BIGINT NULL COMMENT '卖4量',
    ask_volume5 BIGINT NULL COMMENT '卖5量',
    bid_price1 DECIMAL(24,6) NULL COMMENT '买1价',
    bid_price2 DECIMAL(24,6) NULL COMMENT '买2价',
    bid_price3 DECIMAL(24,6) NULL COMMENT '买3价',
    bid_price4 DECIMAL(24,6) NULL COMMENT '买4价',
    bid_price5 DECIMAL(24,6) NULL COMMENT '买5价',
    bid_volume1 BIGINT NULL COMMENT '买1量',
    bid_volume2 BIGINT NULL COMMENT '买2量',
    bid_volume3 BIGINT NULL COMMENT '买3量',
    bid_volume4 BIGINT NULL COMMENT '买4量',
    bid_volume5 BIGINT NULL COMMENT '买5量',
    iopv DECIMAL(24,6) NULL COMMENT '净值估算，仅基金品种有效',
    trading_phase_code VARCHAR(32) NULL COMMENT '交易阶段代码',
    source VARCHAR(64) NOT NULL DEFAULT 'AmazingData' COMMENT '数据来源',
    etl_batch_no VARCHAR(64) NULL COMMENT 'ETL批次号',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (id),
    UNIQUE KEY uk_etf_code_trade_time (etf_code, trade_time),
    KEY idx_trade_time (trade_time),
    KEY idx_etf_code_time (etf_code, trade_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='ETF实时/历史快照表';

CREATE TABLE IF NOT EXISTS etf_market_kline (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    etf_code VARCHAR(16) NOT NULL COMMENT 'ETF代码',
    period VARCHAR(16) NOT NULL COMMENT '周期，如min1/min5/day/week/month',
    trade_time DATETIME(3) NOT NULL COMMENT 'K线时间',
    open_price DECIMAL(24,6) NULL COMMENT '开盘价',
    high_price DECIMAL(24,6) NULL COMMENT '最高价',
    low_price DECIMAL(24,6) NULL COMMENT '最低价',
    close_price DECIMAL(24,6) NULL COMMENT '收盘价',
    volume BIGINT NULL COMMENT '成交量',
    amount DECIMAL(24,4) NULL COMMENT '成交金额',
    source VARCHAR(64) NOT NULL DEFAULT 'AmazingData' COMMENT '数据来源',
    etl_batch_no VARCHAR(64) NULL COMMENT 'ETL批次号',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (id),
    UNIQUE KEY uk_etf_code_period_trade_time (etf_code, period, trade_time),
    KEY idx_trade_time (trade_time),
    KEY idx_etf_code_period_time (etf_code, period, trade_time),
    KEY idx_period_trade_time (period, trade_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='ETF K线表';

CREATE TABLE IF NOT EXISTS etf_pcf_info (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    etf_code VARCHAR(16) NOT NULL COMMENT 'ETF代码',
    trading_day DATE NOT NULL COMMENT '当前交易日',
    pre_trading_day DATE NULL COMMENT '前一交易日',
    creation_redemption_unit BIGINT NULL COMMENT '每个篮子对应的ETF份数',
    max_cash_ratio DECIMAL(12,6) NULL COMMENT '最大现金替代比例',
    publish VARCHAR(4) NULL COMMENT '是否发布IOPV，Y/N',
    creation VARCHAR(4) NULL COMMENT '是否允许申购，Y/N',
    redemption VARCHAR(4) NULL COMMENT '是否允许赎回，Y/N',
    creation_redemption_switch VARCHAR(8) NULL COMMENT '申购赎回切换状态',
    record_num INT NULL COMMENT '深市成份证券数目',
    total_record_num INT NULL COMMENT '所有成份证券数量',
    estimate_cash_component DECIMAL(24,4) NULL COMMENT '预估现金差额',
    cash_component DECIMAL(24,4) NULL COMMENT '前一日现金差额',
    nav_per_cu DECIMAL(24,6) NULL COMMENT '前一日最小申赎单位净值',
    nav DECIMAL(24,6) NULL COMMENT '前一日基金份额净值',
    symbol VARCHAR(128) NULL COMMENT '基金名称',
    fund_management_company VARCHAR(255) NULL COMMENT '基金公司名称',
    underlying_security_id VARCHAR(32) NULL COMMENT '拟合指数代码',
    underlying_security_id_source VARCHAR(16) NULL COMMENT '拟合指数市场',
    dividend_per_cu DECIMAL(24,4) NULL COMMENT '红利金额',
    creation_limit DECIMAL(24,4) NULL COMMENT '累计申购总额限制',
    redemption_limit DECIMAL(24,4) NULL COMMENT '累计赎回总额限制',
    creation_limit_per_user DECIMAL(24,4) NULL COMMENT '单账户累计申购总额限制',
    redemption_limit_per_user DECIMAL(24,4) NULL COMMENT '单账户累计赎回总额限制',
    net_creation_limit DECIMAL(24,4) NULL COMMENT '净申购总额限制',
    net_redemption_limit DECIMAL(24,4) NULL COMMENT '净赎回总额限制',
    net_creation_limit_per_user DECIMAL(24,4) NULL COMMENT '单账户净申购总额限制',
    net_redemption_limit_per_user DECIMAL(24,4) NULL COMMENT '单账户净赎回总额限制',
    source VARCHAR(64) NOT NULL DEFAULT 'AmazingData' COMMENT '数据来源',
    etl_batch_no VARCHAR(64) NULL COMMENT 'ETL批次号',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (id),
    UNIQUE KEY uk_etf_code_trading_day (etf_code, trading_day),
    KEY idx_trading_day (trading_day),
    KEY idx_underlying_security_id (underlying_security_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='ETF每日PCF头信息表';

CREATE TABLE IF NOT EXISTS etf_pcf_constituent (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    etf_code VARCHAR(16) NOT NULL COMMENT 'ETF代码',
    trading_day DATE NOT NULL COMMENT '交易日',
    constituent_code VARCHAR(32) NOT NULL COMMENT '成分证券代码',
    underlying_symbol VARCHAR(128) NULL COMMENT '成分证券简称',
    component_share DECIMAL(24,6) NULL COMMENT '成分证券数量',
    substitute_flag VARCHAR(16) NULL COMMENT '现金替代标志',
    premium_ratio DECIMAL(12,6) NULL COMMENT '溢价比例',
    discount_ratio DECIMAL(12,6) NULL COMMENT '折价比例',
    creation_cash_substitute DECIMAL(24,4) NULL COMMENT '申购替代金额',
    redemption_cash_substitute DECIMAL(24,4) NULL COMMENT '赎回替代金额',
    substitution_cash_amount DECIMAL(24,4) NULL COMMENT '替代总金额',
    underlying_security_id VARCHAR(32) NULL COMMENT '成分证券所属市场ID',
    source VARCHAR(64) NOT NULL DEFAULT 'AmazingData' COMMENT '数据来源',
    etl_batch_no VARCHAR(64) NULL COMMENT 'ETL批次号',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (id),
    UNIQUE KEY uk_etf_day_constituent (etf_code, trading_day, constituent_code),
    KEY idx_trading_day (trading_day),
    KEY idx_constituent_code (constituent_code),
    KEY idx_etf_code_day (etf_code, trading_day)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='ETF每日PCF成分券明细表';

CREATE TABLE IF NOT EXISTS etf_fund_share (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    etf_code VARCHAR(16) NOT NULL COMMENT 'ETF代码',
    change_date DATE NOT NULL COMMENT '变动日期',
    ann_date DATE NULL COMMENT '公告日期',
    fund_share DECIMAL(24,4) NULL COMMENT '基金份额(万份)',
    total_share DECIMAL(24,4) NULL COMMENT '基金总份额(万份)',
    float_share DECIMAL(24,4) NULL COMMENT '流通份额(万份)',
    change_reason VARCHAR(255) NULL COMMENT '份额变动原因',
    is_consolidated_data TINYINT NULL COMMENT '是否合并数据 0非合并 1合并 2合并但该基金代码不实际交易',
    source VARCHAR(64) NOT NULL DEFAULT 'AmazingData' COMMENT '数据来源',
    etl_batch_no VARCHAR(64) NULL COMMENT 'ETL批次号',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (id),
    UNIQUE KEY uk_etf_code_change_date (etf_code, change_date),
    KEY idx_change_date (change_date),
    KEY idx_ann_date (ann_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='ETF基金份额表';

CREATE TABLE IF NOT EXISTS etf_fund_iopv (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    etf_code VARCHAR(16) NOT NULL COMMENT 'ETF代码',
    price_date DATE NOT NULL COMMENT '日期',
    iopv_nav DECIMAL(24,6) NULL COMMENT 'IOPV收盘净值',
    source VARCHAR(64) NOT NULL DEFAULT 'AmazingData' COMMENT '数据来源',
    etl_batch_no VARCHAR(64) NULL COMMENT 'ETL批次号',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (id),
    UNIQUE KEY uk_etf_code_price_date (etf_code, price_date),
    KEY idx_price_date (price_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='ETF每日收盘IOPV表';

CREATE TABLE IF NOT EXISTS etf_ta_indicator (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    etf_code VARCHAR(20) NOT NULL COMMENT 'ETF代码，如 510300.SH',
    period VARCHAR(20) NOT NULL COMMENT '周期：day/week/month/season',
    trade_time DATETIME NOT NULL COMMENT 'K线时间',
    open_price DECIMAL(24,8) NULL COMMENT '开盘价',
    high_price DECIMAL(24,8) NULL COMMENT '最高价',
    low_price DECIMAL(24,8) NULL COMMENT '最低价',
    close_price DECIMAL(24,8) NULL COMMENT '收盘价',
    volume BIGINT NULL COMMENT '成交量',
    amount DECIMAL(24,8) NULL COMMENT '成交额',
    dif DECIMAL(24,8) NULL COMMENT 'MACD-DIF',
    dea DECIMAL(24,8) NULL COMMENT 'MACD-DEA',
    macd DECIMAL(24,8) NULL COMMENT 'MACD柱值，通常为2*(DIF-DEA)',
    is_macd_golden_cross TINYINT NOT NULL DEFAULT 0 COMMENT '本周期是否发生金叉：1是0否',
    is_macd_dead_cross TINYINT NOT NULL DEFAULT 0 COMMENT '本周期是否发生死叉：1是0否',
    is_macd_golden_state TINYINT NOT NULL DEFAULT 0 COMMENT '当前是否处于金叉状态(DIF>DEA)：1是0否',
    is_macd_positive TINYINT NOT NULL DEFAULT 0 COMMENT 'MACD是否大于0：1是0否',
    is_macd_red TINYINT NOT NULL DEFAULT 0 COMMENT 'MACD是否红柱/红豆：1是0否',
    macd_hist_direction TINYINT NOT NULL DEFAULT 0 COMMENT 'MACD柱方向：1增强,-1减弱,0持平/未知',
    sar_value DECIMAL(24,8) NULL COMMENT 'SAR值',
    is_sar_bullish TINYINT NOT NULL DEFAULT 0 COMMENT '是否处于SAR多头状态(close > sar)：1是0否',
    sar_trend TINYINT NOT NULL DEFAULT 0 COMMENT 'SAR趋势方向：1多头,-1空头,0未知',
    ma5 DECIMAL(24,8) NULL COMMENT '5周期均线',
    ma10 DECIMAL(24,8) NULL COMMENT '10周期均线',
    ma20 DECIMAL(24,8) NULL COMMENT '20周期均线',
    ma30 DECIMAL(24,8) NULL COMMENT '30周期均线',
    ma60 DECIMAL(24,8) NULL COMMENT '60周期均线',
    is_ma5_above_ma10 TINYINT NOT NULL DEFAULT 0 COMMENT 'MA5是否在MA10之上：1是0否',
    is_ma10_above_ma20 TINYINT NOT NULL DEFAULT 0 COMMENT 'MA10是否在MA20之上：1是0否',
    is_close_above_ma20 TINYINT NOT NULL DEFAULT 0 COMMENT '收盘价是否高于MA20：1是0否',
    is_close_above_ma60 TINYINT NOT NULL DEFAULT 0 COMMENT '收盘价是否高于MA60：1是0否',
    rsi6 DECIMAL(24,8) NULL COMMENT 'RSI6',
    rsi12 DECIMAL(24,8) NULL COMMENT 'RSI12',
    rsi24 DECIMAL(24,8) NULL COMMENT 'RSI24',
    k_value DECIMAL(24,8) NULL COMMENT 'KDJ-K值',
    d_value DECIMAL(24,8) NULL COMMENT 'KDJ-D值',
    j_value DECIMAL(24,8) NULL COMMENT 'KDJ-J值',
    boll_mid DECIMAL(24,8) NULL COMMENT 'BOLL中轨',
    boll_upper DECIMAL(24,8) NULL COMMENT 'BOLL上轨',
    boll_lower DECIMAL(24,8) NULL COMMENT 'BOLL下轨',
    atr14 DECIMAL(24,8) NULL COMMENT 'ATR14',
    adx14 DECIMAL(24,8) NULL COMMENT 'ADX14',
    signal_trend_long TINYINT NOT NULL DEFAULT 0 COMMENT '综合趋势多头信号：1是0否',
    signal_momentum_long TINYINT NOT NULL DEFAULT 0 COMMENT '综合动量多头信号：1是0否',
    signal_warning TINYINT NOT NULL DEFAULT 0 COMMENT '风险/转弱预警信号：1是0否',
    source VARCHAR(50) NOT NULL DEFAULT 'AmazingData' COMMENT '数据来源',
    etl_batch_no VARCHAR(50) NULL COMMENT 'ETL批次号',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (id),
    UNIQUE KEY uk_etf_ta_indicator (etf_code, period, trade_time),
    KEY idx_etf_code_period_time (etf_code, period, trade_time),
    KEY idx_period_trade_time (period, trade_time),
    KEY idx_trade_time (trade_time),
    KEY idx_signal_trend_long (signal_trend_long),
    KEY idx_signal_momentum_long (signal_momentum_long),
    KEY idx_signal_warning (signal_warning)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='ETF技术指标表(MACD/SAR/MA/RSI/KDJ/BOLL/ATR/ADX)';

CREATE TABLE IF NOT EXISTS etf_five_dimension_resonance (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    etf_code VARCHAR(20) NOT NULL COMMENT 'ETF代码，如510300.SH',
    etf_name VARCHAR(128) NULL COMMENT 'ETF简称',
    trade_date DATE NULL COMMENT '交易日期',
    trade_time DATETIME NULL COMMENT 'K线时间',
    signal_trend_long TINYINT NOT NULL DEFAULT 0 COMMENT '综合趋势多头信号：1是0否',
    signal_momentum_long TINYINT NOT NULL DEFAULT 0 COMMENT '综合动量多头信号：1是0否',
    signal_warning TINYINT NOT NULL DEFAULT 0 COMMENT '风险预警信号：1是0否',
    open_price DECIMAL(24,8) NULL COMMENT '开盘价',
    high_price DECIMAL(24,8) NULL COMMENT '最高价',
    low_price DECIMAL(24,8) NULL COMMENT '最低价',
    close_price DECIMAL(24,8) NULL COMMENT '收盘价',
    volume BIGINT NULL COMMENT '成交量',
    amount DECIMAL(24,8) NULL COMMENT '成交额',
    dif DECIMAL(24,8) NULL COMMENT 'MACD-DIF',
    dea DECIMAL(24,8) NULL COMMENT 'MACD-DEA',
    macd DECIMAL(24,8) NULL COMMENT 'MACD柱值',
    is_macd_golden_state TINYINT NOT NULL DEFAULT 0 COMMENT '是否金叉状态：1是0否',
    is_macd_red TINYINT NOT NULL DEFAULT 0 COMMENT '是否红柱：1是0否',
    macd_hist_direction TINYINT NOT NULL DEFAULT 0 COMMENT 'MACD柱方向：1增强,-1减弱,0持平',
    sar_value DECIMAL(24,8) NULL COMMENT 'SAR值',
    is_sar_bullish TINYINT NOT NULL DEFAULT 0 COMMENT '是否SAR多头：1是0否',
    sar_trend TINYINT NOT NULL DEFAULT 0 COMMENT 'SAR趋势方向：1多头,-1空头,0未知',
    ma5 DECIMAL(24,8) NULL COMMENT 'MA5',
    ma10 DECIMAL(24,8) NULL COMMENT 'MA10',
    ma20 DECIMAL(24,8) NULL COMMENT 'MA20',
    ma30 DECIMAL(24,8) NULL COMMENT 'MA30',
    ma60 DECIMAL(24,8) NULL COMMENT 'MA60',
    is_ma5_above_ma10 TINYINT NOT NULL DEFAULT 0 COMMENT 'MA5在MA10之上：1是0否',
    is_ma10_above_ma20 TINYINT NOT NULL DEFAULT 0 COMMENT 'MA10在MA20之上：1是0否',
    is_close_above_ma20 TINYINT NOT NULL DEFAULT 0 COMMENT '收盘价在MA20之上：1是0否',
    is_close_above_ma60 TINYINT NOT NULL DEFAULT 0 COMMENT '收盘价在MA60之上：1是0否',
    rsi6 DECIMAL(24,8) NULL COMMENT 'RSI6',
    rsi12 DECIMAL(24,8) NULL COMMENT 'RSI12',
    rsi24 DECIMAL(24,8) NULL COMMENT 'RSI24',
    k_value DECIMAL(24,8) NULL COMMENT 'KDJ-K值',
    d_value DECIMAL(24,8) NULL COMMENT 'KDJ-D值',
    j_value DECIMAL(24,8) NULL COMMENT 'KDJ-J值',
    boll_mid DECIMAL(24,8) NULL COMMENT 'BOLL中轨',
    boll_upper DECIMAL(24,8) NULL COMMENT 'BOLL上轨',
    boll_lower DECIMAL(24,8) NULL COMMENT 'BOLL下轨',
    atr14 DECIMAL(24,8) NULL COMMENT 'ATR14',
    adx14 DECIMAL(24,8) NULL COMMENT 'ADX14',
    is_yesterday_triggered TINYINT NOT NULL DEFAULT 0 COMMENT '昨日是否触发五维共振：0否1是',
    is_today_triggered TINYINT NOT NULL DEFAULT 0 COMMENT '今日是否触发五维共振：0否1是',
    first_triggered_date_of_year DATE NULL COMMENT '今年首次触发五维共振日期',
    previous_triggered_date DATE NULL COMMENT '上次触发五维共振日期',
    last_triggered_date DATE NULL COMMENT '最后触发五维共振日期',
    source VARCHAR(64) NOT NULL DEFAULT 'AmazingData' COMMENT '数据来源',
    etl_batch_no VARCHAR(64) NULL COMMENT 'ETL批次号',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (id),
    UNIQUE KEY uk_etf_code_trade_date (etf_code, trade_date),
    KEY idx_etf_code (etf_code),
    KEY idx_etf_name (etf_name),
    KEY idx_trade_time (trade_time),
    KEY idx_last_triggered_date (last_triggered_date),
    KEY idx_close_price (close_price),
    KEY idx_is_today_triggered (is_today_triggered),
    KEY idx_is_yesterday_triggered (is_yesterday_triggered)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='ETF五维共振分析结果表';

CREATE TABLE IF NOT EXISTS etf_five_dimension_report (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    title VARCHAR(255) NOT NULL COMMENT '报告标题',
    content_md LONGTEXT NOT NULL COMMENT 'Markdown正文',
    publisher VARCHAR(64) NOT NULL COMMENT '发布人',
    publish_time DATETIME NOT NULL COMMENT '发布时间',
    is_active TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否有效',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (id),
    KEY idx_publish_time (publish_time),
    KEY idx_publisher (publisher),
    KEY idx_is_active (is_active)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='ETF五维共振报告表';

CREATE TABLE IF NOT EXISTS menu_config (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    menu_code VARCHAR(64) NOT NULL COMMENT '菜单唯一编码',
    menu_name VARCHAR(128) NOT NULL COMMENT '菜单名称',
    parent_code VARCHAR(64) NULL COMMENT '父级菜单编码',
    path VARCHAR(255) NULL COMMENT '前端路由路径',
    icon VARCHAR(64) NULL COMMENT '菜单图标',
    sort INT NOT NULL DEFAULT 0 COMMENT '排序',
    is_visible TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否显示，1显示 0隐藏',
    is_active TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否有效，1有效 0无效',
    remark VARCHAR(255) NULL COMMENT '备注',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (id),
    UNIQUE KEY uk_menu_code (menu_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='菜单配置表';

CREATE TABLE IF NOT EXISTS sys_param (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    param_key VARCHAR(128) NOT NULL COMMENT '参数键',
    param_value VARCHAR(255) NOT NULL COMMENT '参数值',
    description VARCHAR(255) NULL COMMENT '参数描述',
    is_active TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否有效',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (id),
    UNIQUE KEY uk_param_key (param_key)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='系统参数配置表';

CREATE TABLE IF NOT EXISTS sys_user (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    username VARCHAR(64) NOT NULL COMMENT '登录账号',
    password_hash VARCHAR(128) NOT NULL COMMENT '密码哈希值',
    display_name VARCHAR(128) NULL COMMENT '显示名称',
    is_active TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否有效，1有效 0无效',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (id),
    UNIQUE KEY uk_username (username),
    KEY idx_is_active (is_active)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='系统普通用户表';

CREATE TABLE IF NOT EXISTS etl_batch_status (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    batch_no VARCHAR(50) NOT NULL COMMENT '批次号（格式：YYYYMMDD_HHMMSS）',
    job_name VARCHAR(100) NOT NULL COMMENT '任务名称（如：ETF_DATA_ETL）',
    start_time DATETIME NOT NULL COMMENT '任务开始时间',
    end_time DATETIME NULL COMMENT '任务结束时间',
    status VARCHAR(20) NOT NULL DEFAULT 'RUNNING' COMMENT '状态：RUNNING/SUCCESS/FAILED/PARTIAL',
    trade_date_start INT NOT NULL COMMENT '处理起始日期（YYYYMMDD）',
    trade_date_end INT NOT NULL COMMENT '处理结束日期（YYYYMMDD）',
    etf_count INT NULL COMMENT '处理的ETF数量',
    kline_count INT NULL COMMENT '写入的K线数量',
    error_message TEXT NULL COMMENT '错误信息',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_batch_no (batch_no),
    INDEX idx_status (status),
    INDEX idx_trade_date (trade_date_start, trade_date_end)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='ETL跑批状态表';

CREATE TABLE IF NOT EXISTS etl_checkpoint (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    checkpoint_key VARCHAR(100) NOT NULL COMMENT '检查点键（如：ETF_KLINE_DAY）',
    last_trade_date INT NOT NULL COMMENT '最后成功处理的交易日',
    last_batch_no VARCHAR(50) NULL COMMENT '最后成功处理的批次号',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_checkpoint_key (checkpoint_key)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='ETL跑批检查点表';
